version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-tedtalks
    environment:
      POSTGRES_DB: tedtalksdb
      POSTGRES_USER: tedtalks
      POSTGRES_PASSWORD: tedtalks123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  tedtalks-app:
    build: .
    container_name: tedtalks-analyzer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tedtalksdb
      SPRING_DATASOURCE_USERNAME: tedtalks
      SPRING_DATASOURCE_PASSWORD: tedtalks123
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
